version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=lonefootballer
      - POSTGRES_PASSWORD=lonefootballer
    ports:
      - "5432:5432"
    volumes:
      - ./lonefootballer:/var/lib/postgresql/lonefootballer