spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lonefootballer
    username: lonefootballer
    password: lonefootballer
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration

logging:
  level:
    com:
      zaxxer:
        hikari: info
    root: info